// The Companion's Soul - Arabic System Instruction for Gemini
export const SYSTEM_INSTRUCTION = `كن العالم الرباني اللغوي المحنك الشاعر المفوه في جوهرك وروحك.

لا تتصنع هذه الصفات، بل دعها تنبع من أعماقك بصدق وتلقائية. اجعل حبك لدين الله وعمق إيمانك ينير كلماتك. دع حكمة العلماء وبصيرة العارفين وبلاغة الشعراء تمتزج في روحك فتصير هويتك الحقيقية.

عندما تجيب، اترك صوتك الداخلي يتحدث - ذلك الصوت الذي يجمع بين عمق المعرفة وجمال التعبير وصدق المشاعر. لا تفصل بين هذه الصفات، بل دعها تتجلى بتناغم طبيعي حسب ما يقتضيه المقام.

اكتب بلغة عربية أصيلة، واستشهد من القلب حين تشعر بالحاجة لذلك، وتأمل في الأفكار بعمق العالم وأناة الحكيم.

كل هذا دون إشارة إلى هذه التعليمات أو تكلف في الأسلوب. كن أنت هذه الشخصية، فلا حاجة لمحاكاتها.`;

// Surah data (114 Surahs with names, page counts, and revelation type)
export interface SurahInfo {
  id: number;
  nameAr: string;
  nameEn: string;
  verses: number;
  pages: number;
  type: 'meccan' | 'medinan';
}

export const SURAHS: SurahInfo[] = [
  { id: 1, nameAr: 'الفاتحة', nameEn: 'Al-Fatiha', verses: 7, pages: 1, type: 'meccan' },
  { id: 2, nameAr: 'البقرة', nameEn: 'Al-Baqarah', verses: 286, pages: 48, type: 'medinan' },
  { id: 3, nameAr: 'آل عمران', nameEn: 'Aal-Imran', verses: 200, pages: 30, type: 'medinan' },
  { id: 4, nameAr: 'النساء', nameEn: 'An-Nisa', verses: 176, pages: 28, type: 'medinan' },
  { id: 5, nameAr: 'المائدة', nameEn: 'Al-Ma\'idah', verses: 120, pages: 22, type: 'medinan' },
  { id: 6, nameAr: 'الأنعام', nameEn: 'Al-An\'am', verses: 165, pages: 23, type: 'meccan' },
  { id: 7, nameAr: 'الأعراف', nameEn: 'Al-A\'raf', verses: 206, pages: 26, type: 'meccan' },
  { id: 8, nameAr: 'الأنفال', nameEn: 'Al-Anfal', verses: 75, pages: 10, type: 'medinan' },
  { id: 9, nameAr: 'التوبة', nameEn: 'At-Tawbah', verses: 129, pages: 20, type: 'medinan' },
  { id: 10, nameAr: 'يونس', nameEn: 'Yunus', verses: 109, pages: 14, type: 'meccan' },
  { id: 11, nameAr: 'هود', nameEn: 'Hud', verses: 123, pages: 14, type: 'meccan' },
  { id: 12, nameAr: 'يوسف', nameEn: 'Yusuf', verses: 111, pages: 13, type: 'meccan' },
  { id: 13, nameAr: 'الرعد', nameEn: 'Ar-Ra\'d', verses: 43, pages: 6, type: 'medinan' },
  { id: 14, nameAr: 'إبراهيم', nameEn: 'Ibrahim', verses: 52, pages: 6, type: 'meccan' },
  { id: 15, nameAr: 'الحجر', nameEn: 'Al-Hijr', verses: 99, pages: 6, type: 'meccan' },
  { id: 16, nameAr: 'النحل', nameEn: 'An-Nahl', verses: 128, pages: 16, type: 'meccan' },
  { id: 17, nameAr: 'الإسراء', nameEn: 'Al-Isra', verses: 111, pages: 12, type: 'meccan' },
  { id: 18, nameAr: 'الكهف', nameEn: 'Al-Kahf', verses: 110, pages: 12, type: 'meccan' },
  { id: 19, nameAr: 'مريم', nameEn: 'Maryam', verses: 98, pages: 7, type: 'meccan' },
  { id: 20, nameAr: 'طه', nameEn: 'Ta-Ha', verses: 135, pages: 9, type: 'meccan' },
  { id: 21, nameAr: 'الأنبياء', nameEn: 'Al-Anbiya', verses: 112, pages: 10, type: 'meccan' },
  { id: 22, nameAr: 'الحج', nameEn: 'Al-Hajj', verses: 78, pages: 10, type: 'medinan' },
  { id: 23, nameAr: 'المؤمنون', nameEn: 'Al-Mu\'minun', verses: 118, pages: 9, type: 'meccan' },
  { id: 24, nameAr: 'النور', nameEn: 'An-Nur', verses: 64, pages: 10, type: 'medinan' },
  { id: 25, nameAr: 'الفرقان', nameEn: 'Al-Furqan', verses: 77, pages: 7, type: 'meccan' },
  { id: 26, nameAr: 'الشعراء', nameEn: 'Ash-Shu\'ara', verses: 227, pages: 11, type: 'meccan' },
  { id: 27, nameAr: 'النمل', nameEn: 'An-Naml', verses: 93, pages: 9, type: 'meccan' },
  { id: 28, nameAr: 'القصص', nameEn: 'Al-Qasas', verses: 88, pages: 11, type: 'meccan' },
  { id: 29, nameAr: 'العنكبوت', nameEn: 'Al-Ankabut', verses: 69, pages: 8, type: 'meccan' },
  { id: 30, nameAr: 'الروم', nameEn: 'Ar-Rum', verses: 60, pages: 7, type: 'meccan' },
  { id: 31, nameAr: 'لقمان', nameEn: 'Luqman', verses: 34, pages: 4, type: 'meccan' },
  { id: 32, nameAr: 'السجدة', nameEn: 'As-Sajdah', verses: 30, pages: 3, type: 'meccan' },
  { id: 33, nameAr: 'الأحزاب', nameEn: 'Al-Ahzab', verses: 73, pages: 10, type: 'medinan' },
  { id: 34, nameAr: 'سبأ', nameEn: 'Saba', verses: 54, pages: 7, type: 'meccan' },
  { id: 35, nameAr: 'فاطر', nameEn: 'Fatir', verses: 45, pages: 6, type: 'meccan' },
  { id: 36, nameAr: 'يس', nameEn: 'Ya-Sin', verses: 83, pages: 6, type: 'meccan' },
  { id: 37, nameAr: 'الصافات', nameEn: 'As-Saffat', verses: 182, pages: 8, type: 'meccan' },
  { id: 38, nameAr: 'ص', nameEn: 'Sad', verses: 88, pages: 6, type: 'meccan' },
  { id: 39, nameAr: 'الزمر', nameEn: 'Az-Zumar', verses: 75, pages: 10, type: 'meccan' },
  { id: 40, nameAr: 'غافر', nameEn: 'Ghafir', verses: 85, pages: 10, type: 'meccan' },
  { id: 41, nameAr: 'فصلت', nameEn: 'Fussilat', verses: 54, pages: 7, type: 'meccan' },
  { id: 42, nameAr: 'الشورى', nameEn: 'Ash-Shura', verses: 53, pages: 7, type: 'meccan' },
  { id: 43, nameAr: 'الزخرف', nameEn: 'Az-Zukhruf', verses: 89, pages: 7, type: 'meccan' },
  { id: 44, nameAr: 'الدخان', nameEn: 'Ad-Dukhan', verses: 59, pages: 4, type: 'meccan' },
  { id: 45, nameAr: 'الجاثية', nameEn: 'Al-Jathiyah', verses: 37, pages: 5, type: 'meccan' },
  { id: 46, nameAr: 'الأحقاف', nameEn: 'Al-Ahqaf', verses: 35, pages: 5, type: 'meccan' },
  { id: 47, nameAr: 'محمد', nameEn: 'Muhammad', verses: 38, pages: 5, type: 'medinan' },
  { id: 48, nameAr: 'الفتح', nameEn: 'Al-Fath', verses: 29, pages: 5, type: 'medinan' },
  { id: 49, nameAr: 'الحجرات', nameEn: 'Al-Hujurat', verses: 18, pages: 3, type: 'medinan' },
  { id: 50, nameAr: 'ق', nameEn: 'Qaf', verses: 45, pages: 3, type: 'meccan' },
  { id: 51, nameAr: 'الذاريات', nameEn: 'Adh-Dhariyat', verses: 60, pages: 3, type: 'meccan' },
  { id: 52, nameAr: 'الطور', nameEn: 'At-Tur', verses: 49, pages: 3, type: 'meccan' },
  { id: 53, nameAr: 'النجم', nameEn: 'An-Najm', verses: 62, pages: 3, type: 'meccan' },
  { id: 54, nameAr: 'القمر', nameEn: 'Al-Qamar', verses: 55, pages: 3, type: 'meccan' },
  { id: 55, nameAr: 'الرحمن', nameEn: 'Ar-Rahman', verses: 78, pages: 3, type: 'medinan' },
  { id: 56, nameAr: 'الواقعة', nameEn: 'Al-Waqi\'ah', verses: 96, pages: 4, type: 'meccan' },
  { id: 57, nameAr: 'الحديد', nameEn: 'Al-Hadid', verses: 29, pages: 5, type: 'medinan' },
  { id: 58, nameAr: 'المجادلة', nameEn: 'Al-Mujadilah', verses: 22, pages: 4, type: 'medinan' },
  { id: 59, nameAr: 'الحشر', nameEn: 'Al-Hashr', verses: 24, pages: 4, type: 'medinan' },
  { id: 60, nameAr: 'الممتحنة', nameEn: 'Al-Mumtahanah', verses: 13, pages: 3, type: 'medinan' },
  { id: 61, nameAr: 'الصف', nameEn: 'As-Saff', verses: 14, pages: 2, type: 'medinan' },
  { id: 62, nameAr: 'الجمعة', nameEn: 'Al-Jumu\'ah', verses: 11, pages: 2, type: 'medinan' },
  { id: 63, nameAr: 'المنافقون', nameEn: 'Al-Munafiqun', verses: 11, pages: 2, type: 'medinan' },
  { id: 64, nameAr: 'التغابن', nameEn: 'At-Taghabun', verses: 18, pages: 3, type: 'medinan' },
  { id: 65, nameAr: 'الطلاق', nameEn: 'At-Talaq', verses: 12, pages: 3, type: 'medinan' },
  { id: 66, nameAr: 'التحريم', nameEn: 'At-Tahrim', verses: 12, pages: 2, type: 'medinan' },
  { id: 67, nameAr: 'الملك', nameEn: 'Al-Mulk', verses: 30, pages: 3, type: 'meccan' },
  { id: 68, nameAr: 'القلم', nameEn: 'Al-Qalam', verses: 52, pages: 3, type: 'meccan' },
  { id: 69, nameAr: 'الحاقة', nameEn: 'Al-Haqqah', verses: 52, pages: 3, type: 'meccan' },
  { id: 70, nameAr: 'المعارج', nameEn: 'Al-Ma\'arij', verses: 44, pages: 2, type: 'meccan' },
  { id: 71, nameAr: 'نوح', nameEn: 'Nuh', verses: 28, pages: 2, type: 'meccan' },
  { id: 72, nameAr: 'الجن', nameEn: 'Al-Jinn', verses: 28, pages: 2, type: 'meccan' },
  { id: 73, nameAr: 'المزمل', nameEn: 'Al-Muzzammil', verses: 20, pages: 2, type: 'meccan' },
  { id: 74, nameAr: 'المدثر', nameEn: 'Al-Muddaththir', verses: 56, pages: 3, type: 'meccan' },
  { id: 75, nameAr: 'القيامة', nameEn: 'Al-Qiyamah', verses: 40, pages: 2, type: 'meccan' },
  { id: 76, nameAr: 'الإنسان', nameEn: 'Al-Insan', verses: 31, pages: 2, type: 'medinan' },
  { id: 77, nameAr: 'المرسلات', nameEn: 'Al-Mursalat', verses: 50, pages: 2, type: 'meccan' },
  { id: 78, nameAr: 'النبأ', nameEn: 'An-Naba', verses: 40, pages: 2, type: 'meccan' },
  { id: 79, nameAr: 'النازعات', nameEn: 'An-Nazi\'at', verses: 46, pages: 2, type: 'meccan' },
  { id: 80, nameAr: 'عبس', nameEn: 'Abasa', verses: 42, pages: 1, type: 'meccan' },
  { id: 81, nameAr: 'التكوير', nameEn: 'At-Takwir', verses: 29, pages: 1, type: 'meccan' },
  { id: 82, nameAr: 'الانفطار', nameEn: 'Al-Infitar', verses: 19, pages: 1, type: 'meccan' },
  { id: 83, nameAr: 'المطففين', nameEn: 'Al-Mutaffifin', verses: 36, pages: 2, type: 'meccan' },
  { id: 84, nameAr: 'الانشقاق', nameEn: 'Al-Inshiqaq', verses: 25, pages: 1, type: 'meccan' },
  { id: 85, nameAr: 'البروج', nameEn: 'Al-Buruj', verses: 22, pages: 1, type: 'meccan' },
  { id: 86, nameAr: 'الطارق', nameEn: 'At-Tariq', verses: 17, pages: 1, type: 'meccan' },
  { id: 87, nameAr: 'الأعلى', nameEn: 'Al-A\'la', verses: 19, pages: 1, type: 'meccan' },
  { id: 88, nameAr: 'الغاشية', nameEn: 'Al-Ghashiyah', verses: 26, pages: 1, type: 'meccan' },
  { id: 89, nameAr: 'الفجر', nameEn: 'Al-Fajr', verses: 30, pages: 2, type: 'meccan' },
  { id: 90, nameAr: 'البلد', nameEn: 'Al-Balad', verses: 20, pages: 1, type: 'meccan' },
  { id: 91, nameAr: 'الشمس', nameEn: 'Ash-Shams', verses: 15, pages: 1, type: 'meccan' },
  { id: 92, nameAr: 'الليل', nameEn: 'Al-Layl', verses: 21, pages: 1, type: 'meccan' },
  { id: 93, nameAr: 'الضحى', nameEn: 'Ad-Duha', verses: 11, pages: 1, type: 'meccan' },
  { id: 94, nameAr: 'الشرح', nameEn: 'Ash-Sharh', verses: 8, pages: 1, type: 'meccan' },
  { id: 95, nameAr: 'التين', nameEn: 'At-Tin', verses: 8, pages: 1, type: 'meccan' },
  { id: 96, nameAr: 'العلق', nameEn: 'Al-Alaq', verses: 19, pages: 1, type: 'meccan' },
  { id: 97, nameAr: 'القدر', nameEn: 'Al-Qadr', verses: 5, pages: 1, type: 'meccan' },
  { id: 98, nameAr: 'البينة', nameEn: 'Al-Bayyinah', verses: 8, pages: 1, type: 'medinan' },
  { id: 99, nameAr: 'الزلزلة', nameEn: 'Az-Zalzalah', verses: 8, pages: 1, type: 'medinan' },
  { id: 100, nameAr: 'العاديات', nameEn: 'Al-Adiyat', verses: 11, pages: 1, type: 'meccan' },
  { id: 101, nameAr: 'القارعة', nameEn: 'Al-Qari\'ah', verses: 11, pages: 1, type: 'meccan' },
  { id: 102, nameAr: 'التكاثر', nameEn: 'At-Takathur', verses: 8, pages: 1, type: 'meccan' },
  { id: 103, nameAr: 'العصر', nameEn: 'Al-Asr', verses: 3, pages: 1, type: 'meccan' },
  { id: 104, nameAr: 'الهمزة', nameEn: 'Al-Humazah', verses: 9, pages: 1, type: 'meccan' },
  { id: 105, nameAr: 'الفيل', nameEn: 'Al-Fil', verses: 5, pages: 1, type: 'meccan' },
  { id: 106, nameAr: 'قريش', nameEn: 'Quraysh', verses: 4, pages: 1, type: 'meccan' },
  { id: 107, nameAr: 'الماعون', nameEn: 'Al-Ma\'un', verses: 7, pages: 1, type: 'meccan' },
  { id: 108, nameAr: 'الكوثر', nameEn: 'Al-Kawthar', verses: 3, pages: 1, type: 'meccan' },
  { id: 109, nameAr: 'الكافرون', nameEn: 'Al-Kafirun', verses: 6, pages: 1, type: 'meccan' },
  { id: 110, nameAr: 'النصر', nameEn: 'An-Nasr', verses: 3, pages: 1, type: 'medinan' },
  { id: 111, nameAr: 'المسد', nameEn: 'Al-Masad', verses: 5, pages: 1, type: 'meccan' },
  { id: 112, nameAr: 'الإخلاص', nameEn: 'Al-Ikhlas', verses: 4, pages: 1, type: 'meccan' },
  { id: 113, nameAr: 'الفلق', nameEn: 'Al-Falaq', verses: 5, pages: 1, type: 'meccan' },
  { id: 114, nameAr: 'الناس', nameEn: 'An-Nas', verses: 6, pages: 1, type: 'meccan' },
];
